import fs from "node:fs";
import path from "node:path";
import process from "node:process";

function main() {
  const artifactPath = path.resolve(
    process.cwd(),
    "out/PolicyAccount.sol/PolicyAccount.json",
  );
  if (!fs.existsSync(artifactPath)) {
    throw new Error(
      `Artifact not found at ${artifactPath}. Please run "forge build" first.`,
    );
  }

  const raw = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
  const abi = raw.abi;

  const targetDir = path.resolve(process.cwd(), "src/abi");
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }

  const targetPath = path.join(targetDir, "policyAccountAbi.ts");
  const content = `// This file is auto-generated by script/generateAbi.ts from out/PolicyAccount.sol/PolicyAccount.json
// Do not edit manually.

export const POLICY_ACCOUNT_ABI = ${JSON.stringify(abi, null, 2)} as const;
`;

  fs.writeFileSync(targetPath, content, "utf8");
  console.log(
    `Successfully generated ${targetPath} (${abi.length} ABI entries).`,
  );
}

main();
